$schema: https://cdn.jsdelivr.net/npm/@micro-lc/interfaces@latest/schemas/v2/config.schema.json
version: 2

layout:
  content: |
    <link rel="stylesheet" href="./style.css">
    <div class="top-bar layout">Layout</div>
    <div class="layout-content">
      <div class="side-bar layout">
        <span>Layout</span>
      </div>
      <slot></slot>
    </div>

applications:
  home:
    integrationMode: compose
    route: ./
    config:
      content: <div class="content">Content</div>
