$schema: https://cdn.jsdelivr.net/npm/@micro-lc/interfaces@latest/schemas/v2/config.schema.json
version: 2

settings:
  defaultUrl: ./orders

layout:
  sources: https://cdn.jsdelivr.net/npm/@micro-lc/layout@latest/dist/mlc-layout.js
  content:
    - tag: mlc-layout
      properties:
        mode: overlaySideBar
        logo:
          url: ../../../../img/favicon.png
        menuItems:
          - icon:
              library: '@ant-design/icons-svg'
              selector: ShoppingOutlined
            id: orders
            label: Orders
            type: application
          - id: products
            icon:
              library: '@ant-design/icons-svg'
              selector: TagsOutlined
            label: Products
            type: category
            children:
              - icon:
                  library: '@ant-design/icons-svg'
                  selector: SkinOutlined
                id: t-shirts
                label: T-shirts
                type: application
              - icon:
                  library: '@ant-design/icons-svg'
                  selector: RocketOutlined
                id: rockets
                label: Rockets
                type: application
          - id: users
            icon:
              library: '@ant-design/icons-svg'
              selector: UserOutlined
            label: Users
            type: category
            children:
              - icon:
                  library: '@ant-design/icons-svg'
                  selector: TeamOutlined
                id: customers
                label: Customers
                type: application
              - id: personnel
                label: Personnel
                type: group
                children:
                  - icon:
                      library: '@ant-design/icons-svg'
                      selector: CrownOutlined
                    id: admins
                    label: Admins
                    type: application
                  - icon:
                      library: '@ant-design/icons-svg'
                      selector: SmileOutlined
                    id: salespeople
                    label: Salespeople
                    type: application

applications:
  orders:
    integrationMode: compose
    route: ./orders
    config:
      content:
        - tag: div
          attributes:
            class: content
          content: Orders
  t-shirts:
    integrationMode: compose
    route: ./t-shirts
    config:
      content:
        - tag: div
          attributes:
            class: content
          content: T-shirts
  rockets:
    integrationMode: compose
    route: ./rockets
    config:
      content:
        - tag: div
          attributes:
            class: content
          content: Rockets
  customers:
    integrationMode: compose
    route: ./customers
    config:
      content:
        - tag: div
          attributes:
            class: content
          content: Customers
  admins:
    integrationMode: compose
    route: ./admins
    config:
      content:
        - tag: div
          attributes:
            class: content
          content: Admins
  salespeople:
    integrationMode: compose
    route: ./salespeople
    config:
      content:
        - tag: div
          attributes:
            class: content
          content: Salespeople
