$schema: https://unpkg.com/@micro-lc/interfaces@latest/schemas/v2/config.schema.json
version: 2

layout:
  content: |
    <link rel="stylesheet" href="./style.css">

    <div class="layout-container">
      <div class="layout">
        <p style="margin: 0;">
          This is a constructed layout
        </p>
      </div>
      <slot></slot>
    </div>

applications:
  home:
    integrationMode: compose
    route: "./"
    config:
      content:
        - tag: div
          attributes:
            class: content
          content:
            tag: p
            content: This is a constructed content
