$schema: https://cdn.jsdelivr.net/npm/@micro-lc/interfaces@latest/schemas/v2/config.schema.json
version: 2

layout:
  sources: https://cdn.jsdelivr.net/npm/@micro-lc/layout@latest/dist/mlc-layout.js
  content:
    - tag: mlc-layout
      properties:
        mode: topBar
        logo:
          url: ../../../../img/favicon.png
        userMenu:
          logout:
            method: POST
            url: .
          userInfoUrl: ./userinfo.json
          userPropertiesMapping:
            image: avatar

applications:
  home:
    integrationMode: compose
    route: ./
    config:
      content:
        - tag: div
          attributes:
            class: content
