"$schema": https://cdn.jsdelivr.net/npm/@micro-lc/interfaces@latest/schemas/v2/config.schema.json
"version": 2

settings:
  defaultUrl: ./401

layout:
  sources: https://cdn.jsdelivr.net/npm/@micro-lc/layout@latest/dist/mlc-layout.js
  content:
    - tag: mlc-layout
      properties:
        mode: topBar
        logo:
          url: ../../../../img/favicon.png
        menuItems:
          - icon:
              library: '@ant-design/icons-svg'
              selector: LockOutlined
            id: 401-error
            label: 401 error
            type: application
          - icon:
              library: '@ant-design/icons-svg'
              selector: QuestionCircleOutlined
            id: 404-error
            label: 404 error
            type: application
          - icon:
              library: '@ant-design/icons-svg'
              selector: MehOutlined
            id: 500-error
            label: 500 error
            type: application

applications:
  401-error:
    integrationMode: parcel
    route: ./401
    entry: https://cdn.jsdelivr.net/npm/@micro-lc/orchestrator@0.1.0/dist/assets/401.baa51327.html

  404-error:
    integrationMode: parcel
    route: ./404
    entry: https://cdn.jsdelivr.net/npm/@micro-lc/orchestrator@0.1.0/dist/assets/404.81641852.html

  500-error:
    integrationMode: parcel
    route: ./500
    entry: https://cdn.jsdelivr.net/npm/@micro-lc/orchestrator@0.1.0/dist/assets/500.10478814.html
